### ISSUE TITLE
Maintain a separate list of Superusers

### ISSUE THREAD

**Issue by aryanc403** [aryanc403/remind#30]
Only people with role ids in this list should be allowed to execute SuperUser only commands. Inclusion/Exclusion of user-id should be manually. One shouldn't be able to change this list using bot commands.
Superusers should only be added by manual intervention on the bot's hosting server.

**Comment by Mohammad-Yasser** [comment]
Why can't it be a specific role, like BotAdmin or ContestReminderAdmin?

**Comment by aryanc403** [comment]
If the bot is supposed to support multiple guilds and/or the public. Then anyone would be to run `t;meta kill/restart` commands by creating the same role on their own server. And hence a need for superusers. 
Saying Admin only command is misleading I will change the title.
